# Generated by Django 4.0.5 on 2023-06-26 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="position",
            old_name="buy_price",
            new_name="buyPrice",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="sell_price",
            new_name="sellPrice",
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
