# Generated by Django 4.0.5 on 2023-06-26 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0002_rename_buy_price_position_buyprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="PnL",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="closingTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="position",
            name="openingTime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
