# Generated by Django 4.0.5 on 2023-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0004_alter_position_pnl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="PnL",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=10, null=True
            ),
        ),
    ]
