# Generated by Django 4.0.5 on 2023-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0005_alter_position_pnl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="PnL",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="buyPrice",
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="sellPrice",
            field=models.DecimalField(decimal_places=20, max_digits=50, null=True),
        ),
    ]
