# Generated by Django 4.0.5 on 2023-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0006_alter_position_pnl_alter_position_buyprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="bybitOrderId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=10,
            ),
        ),
    ]
