# Generated by Django 4.2.2 on 2023-11-20 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0007_position_bybitorderid_alter_position_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("details", models.JSONField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Dev", "Developer"),
                            ("User", "User"),
                        ],
                        default="User",
                        max_length=10,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Advanced", "Advanced"),
                            ("VIP", "VIP"),
                        ],
                        default="Basic",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
