# Generated by Django 4.2.2 on 2023-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0008_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
