# Generated by Django 4.2.2 on 2023-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_center", "0011_user_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notifications",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="stripe_customer_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
